# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
"
RUST_MIN_VER="1.88"

inherit cargo

DESCRIPTION="Better \`pre-commit\`, re-engineered in Rust"
HOMEPAGE="https://prek.j178.dev/"
SRC_URI="
	https://github.com/j178/prek/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		prek-0.3.2-crates.tar.xz
	"
fi

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD CDDL
	CDLA-Permissive-2.0 ISC MIT Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

src_install() {
	cargo_src_install --path crates/prek
}
